import streamlit as st
import os
import sys
import uuid
from PIL import Image
from langchain_core.messages import HumanMessage, AIMessage

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from core.main import build_graph
from core.config import setup_environment

setup_environment()

st.set_page_config(page_title="Automated Financial Analyst", page_icon="📈", layout="wide")

if "thread_id" not in st.session_state:
    st.session_state.thread_id = str(uuid.uuid4())

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

st.title("📈 Automated Financial Analyst")
st.markdown("""
Welcome to the AI Investment Firm. Ask me to analyze Tesla's risks or generate financial visualizations!
""")

# 1. Display the ongoing chat history
for msg in st.session_state.chat_history:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("image") and os.path.exists(msg["image"]):
            try:
                img = Image.open(msg["image"])
                st.image(img, caption="Generated by Data Scientist (Coder Agent)")
            except Exception as e:
                st.error(f"Could not load image: {e}")

prompt = st.chat_input("Ask a financial question or ask to generate a chart...")

if prompt:
    st.session_state.chat_history.append({"role": "user", "content": prompt, "image": None})
    with st.chat_message("user"):
        st.write(prompt)

    with st.spinner("The Manager is orchestrating the team..."):
        try:
            graph = build_graph()
            
            initial_state = {
                "messages": [HumanMessage(content=prompt)], 
                "revision_number": 0,
                "revenue_data": "Q1: $21B, Q2: $24B, Q3: $23B, Q4: $25B"
            }
            
            config = {"configurable": {"thread_id": st.session_state.thread_id}}
            final_state = graph.invoke(initial_state, config=config)
            
            ai_response = final_state.get("draft_answer", "No response generated.")
            
            chart_path = final_state.get("chart_path", "")
            valid_image_path = None
            
            chart_keywords = ['plot', 'chart', 'graph', 'visual']
            if any(word in prompt.lower() for word in chart_keywords):
                if chart_path and os.path.exists(chart_path) and chart_path.endswith('.png'):
                    valid_image_path = chart_path

            st.session_state.chat_history.append({
                "role": "assistant", 
                "content": ai_response, 
                "image": valid_image_path
            })

            with st.chat_message("assistant"):
                st.write(ai_response)
                if valid_image_path:
                    try:
                        img = Image.open(valid_image_path)
                        st.image(img, caption="Generated by Data Scientist (Coder Agent)")
                    except Exception as e:
                        st.error(f"Failed to display chart: {e}")
                        
        except Exception as e:
            error_msg = str(e)
            if "429" in error_msg or "402" in error_msg or "Rate limit" in error_msg:
                friendly_err = "⚠️ API Rate Limit Exceeded"
            else:
                friendly_err = f"⚠️ An unexpected error occurred: {error_msg}"
            
            # error in chat UI
            st.session_state.chat_history.append({
                "role": "assistant", 
                "content": friendly_err, 
                "image": None
            })
            with st.chat_message("assistant"):
                st.error(friendly_err)

st.divider()
st.caption("Made with LangGraph, Streamlit, and OpenRouter")
